### ISSUE TITLE
doesn't work anymore

### ISSUE THREAD

**Issue by fawni** [GhostMander/Dusk-to-Dawn-Settings#1]
raw link needs to be updated

**Comment by ghostmander** [comment]
Fixed. No fetch needed, I just accidentally removed the repo containing the source file... Sorry for inconvinience!

**Comment by giren7384** [comment]
doesnt work again :/

**Comment by ghostmander** [comment]
Try reinstalling the theme, it works just fine for me (`cd powercord\src\Powercord\themes && git clone https://github.com/GhostMander/Dusk-to-Dawn-Settings`)
